#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S2,     sensor_arm_left_angle, sensorI2CCustom)
#pragma config(Sensor, S3,     sensor_arm_right_angle, sensorI2CCustom)
#pragma config(Sensor, S4,     HTSPB,          sensorI2CCustom9V)
#pragma config(Motor,  motorA,          nxtmotor_flapper_left,     tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          nxtmotor_flapper_right,    tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC, nxtmotor_JSG, tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     drive_motor_1, tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     drive_motor_2, tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     arm_motor_left, tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     arm_motor_right, tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     drive_motor_3, tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     drive_motor_4, tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C4_1,    servo_clip_right,     tServoStandard)
#pragma config(Servo,  srvo_S1_C4_2,    servo_clip_left,      tServoStandard)
#pragma config(Servo,  srvo_S1_C4_3,    servo_left_hand_bottom, tServoStandard)
#pragma config(Servo,  srvo_S1_C4_4,    servo_left_hand_top,  tServoStandard)
#pragma config(Servo,  srvo_S1_C4_5,    servo_right_hand_bottom, tServoStandard)
#pragma config(Servo,  srvo_S1_C4_6,    servo_right_hand_top, tServoStandard)
//*!!Code automatically generated by 5'ROBOTC' configuration wizard               !!*//

#include "R2_const.h"

// Global Variable for Robot
int arm_left_pos  = 0;
int arm_right_pos = 0;
int arm_left_target  = ARM_TARGET_NONE;
int arm_right_target = ARM_TARGET_NONE;
bool arm_left_moving_up_to_target    = false;
bool arm_left_moving_down_to_target  = false;
bool arm_right_moving_up_to_target   = false;
bool arm_right_moving_down_to_target = false;

bool arm_left_up_pressed    = false;
bool arm_left_down_pressed  = false;
bool arm_right_up_pressed   = false;
bool arm_right_down_pressed = false;

int arm_clip_pos = ARM_CLIP_PARK;
int flipper_pos = FLIPPER_DOWN;
int JSG_target = 0;
int sensor_IR=sensor_arm_left_angle;



int left_hand_bottom_pos  = HAND_CLOSE;
int left_hand_upper_pos   = HAND_UP;
int right_hand_bottom_pos = HAND_CLOSE;
int right_hand_upper_pos  = HAND_UP;
TTimers timer_left_hand_roll  = T1;
TTimers timer_right_hand_roll = T2;
TTimers timer_clipping = T3;
TTimers timer_R2_sys = T4;
int timer_left_arm;
int timer_right_arm;
int timer_protect_left_move;
int timer_protect_right_move;
int timer_o_c_hand;
int timer_flipping;
int timer_JOY2_BUTTON_X;
int timer_JOY2_BUTTON_B;


#include <JoystickDriver.c>
#include "drivers/hitechnic-angle.h"
#include "drivers/HTSPB-driver.h"
#include "drivers/hitechnic-irseeker-v2.h"
#include "R2_lib.h"

void display_program_info(){
	eraseDisplay();
	nxtDisplayCenteredTextLine(1, "FTc tEaM 1032");
	nxtDisplayCenteredTextLine(3, "Robot Test Program");
	nxtDisplayCenteredTextLine(4, "ver:1");
	nxtDisplayCenteredTextLine(5, "2013.1");
	nxtDisplayCenteredTextLine(7, "dAdAlElE");
	wait1Msec(3000);
	eraseDisplay();

};

void init()
{
	RunAt(0, 0, 0);

  motor[nxtmotor_flapper_left] = 0;                // reset the Motor Encoder of Motor B
  motor[nxtmotor_flapper_right] = 0;                // reset the Motor Encoder of Motor C

	nMotorEncoder[nxtmotor_flapper_left] = 0;                // reset the Motor Encoder of Motor B
  nMotorEncoder[nxtmotor_flapper_right] = 0;                // reset the Motor Encoder of Motor C


	arm_pickup_park();
	hand_all_close();

  init_IR_sensor();
  init_prototype_board();

  wait1Msec(2000);

  ClearTimer(timer_R2_sys);
  timer_left_arm  = 0;
  timer_right_arm = 0;
  timer_protect_left_move=0;
  timer_protect_right_move=0;
  timer_o_c_hand=0;
  timer_JOY2_BUTTON_X=0;
  timer_JOY2_BUTTON_B=0;

  ClearTimer(timer_left_hand_roll);
	ClearTimer(timer_right_hand_roll);
	ClearTimer(timer_clipping);
};


void init_arm_pos()
{
	bool arm_left_touch_bottom, arm_right_touch_bottom;
	ClearTimer(T1);
	arm_left_touch_bottom=is_arm_left_touch_bottom();
	arm_right_touch_bottom=is_arm_right_touch_bottom();

  while(true)
	{

    nxtDisplayTextLine(0, "%d, %d",arm_left_touch_bottom, arm_right_touch_bottom);
		if (arm_left_touch_bottom!=is_arm_left_touch_bottom()){
	  	arm_left_touch_bottom=is_arm_left_touch_bottom();
		  PlaySound(soundBeepBeep);
		};
		if (arm_right_touch_bottom!=is_arm_right_touch_bottom()){
  		arm_right_touch_bottom=is_arm_right_touch_bottom();
		  PlaySound(soundBeepBeep);
		};

		if (arm_left_touch_bottom & arm_right_touch_bottom)
			break;

	  if (time1[T1]>1000) {
      PlaySound(soundBlip);
     	ClearTimer(T1);
    };
	};
	reset_angle_sensor();

	arm_left_target = ARM_TARGET_NONE;
  arm_right_target = ARM_TARGET_NONE;
  }
void auto_right()
	{
		motor[nxtmotor_JSG] = 0;
  	nMotorEncoder[nxtmotor_JSG] = 0;
		motor[nxtmotor_JSG] = 30;
		wait1Msec(300);
		motor[nxtmotor_JSG] = 0;
		wait1Msec(10);
		motor[nxtmotor_flapper_left]=30;
		motor[nxtmotor_flapper_right]=30;
		wait1Msec(500);
		motor[nxtmotor_flapper_left]=-30;
		motor[nxtmotor_flapper_right]=-30;
		wait1Msec(500);
		motor[nxtmotor_flapper_left]=0;
		motor[nxtmotor_flapper_right]=0;
		wait1Msec(100);
		RunAt(40,0,0);
		wait1Msec(1000);
	  RunAt(0,0,-30);
	  wait1Msec(300);
	  RunAt(0,50,0);
	  wait1Msec(2000);
		RunAt(-30,0,0);
	  wait1Msec(500);
		RunAt(0,50,0);
		wait1Msec(1000);
		RunAt(30,0,0);
		wait1Msec(420);
		RunAt(0,50,0);
		wait1Msec(1000);
		RunAt(0,0,30);
		wait1Msec(290);
		RunAt(0,0,0);
		wait1Msec(10);
	}
	void auto_middle()
	{
		motor[nxtmotor_JSG] = 0;
  	nMotorEncoder[nxtmotor_JSG] = 0;
		motor[nxtmotor_JSG] = 30;
		wait1Msec(300);
		motor[nxtmotor_JSG] = 0;
		wait1Msec(10);
		motor[nxtmotor_flapper_left]=30;
		motor[nxtmotor_flapper_right]=30;
		wait1Msec(500);
		motor[nxtmotor_flapper_left]=-30;
		motor[nxtmotor_flapper_right]=-30;
		wait1Msec(500);
		motor[nxtmotor_flapper_left]=0;
		motor[nxtmotor_flapper_right]=0;
		wait1Msec(100);
		RunAt(-30,0,0);
		wait1Msec(400);
	  RunAt(0,50,0);
	  wait1Msec(800);
	  RunAt(0,0,-30);
	  wait1Msec(400);
		RunAt(0,50,0);
	  wait1Msec(1000);
		RunAt(30,0,0);
		wait1Msec(1000);
		RunAt(0,50,0);
		wait1Msec(500);
		RunAt(-30,0,0);
		wait1Msec(500);
		RunAt(0,30,0);
		wait1Msec(1000);
		RunAt(0,0,30);
		wait1Msec(150);
		RunAt(0,0,0);
		wait1Msec(10);

	}
	void auto_left()
	{
		motor[nxtmotor_JSG] = 0;
  	nMotorEncoder[nxtmotor_JSG] = 0;
		motor[nxtmotor_JSG] = -30;
		wait1Msec(300);
		motor[nxtmotor_JSG] = 0;
		wait1Msec(10);
		motor[nxtmotor_flapper_left]=30;
		motor[nxtmotor_flapper_right]=30;
		wait1Msec(500);
		motor[nxtmotor_flapper_left]=-30;
		motor[nxtmotor_flapper_right]=-30;
		wait1Msec(500);
		motor[nxtmotor_flapper_left]=0;
		motor[nxtmotor_flapper_right]=0;
		wait1Msec(100);
		RunAt(-30,0,0);
		wait1Msec(320);
	  RunAt(0,50,0);
	  wait1Msec(800);
	  RunAt(0,0,-30);
	  wait1Msec(550);
		RunAt(0,50,0);
	  wait1Msec(1000);
		RunAt(30,0,0);
		wait1Msec(1360);
		RunAt(0,50,0);
		wait1Msec(500);
		RunAt(-30,0,0);
		wait1Msec(500);
		RunAt(0,30,0);
		wait1Msec(1000);
		RunAt(0,0,-30);
		wait1Msec(200);
		RunAt(0,0,0);
		wait1Msec(10);

	}
task main()
{


	int hongwai;
	int left_arm_pos;
	int right_arm_pos;
	init();
	init_arm_pos();
	left_arm_pos=get_arm_left_pos();
	right_arm_pos=get_arm_right_pos();
	hongwai=get_IR_direction();
	RunAt(0,100,0);
	wait1Msec(1500);
	RunAt(50,50,0);
	wait1Msec(200);
	RunAt(0,100,0);
	wait1Msec(1400);
	RunAt(0,0,0);
	wait1Msec(10);
	hongwai=get_IR_direction();
	if((hongwai==3) || (hongwai==4))
	{
		auto_middle();
		while(right_arm_pos<2000)
		{
			arm_right_up(100);
			right_arm_pos=get_arm_right_pos();
		}
		arm_right_stop();
		servo_right_hand_top_MoveToDeg(HAND_RIGHT_TOP_GUA_ANG,SERVO_SPEED_NORMAL);
		servo_right_hand_bottom_MoveToDeg(HAND_RIGHT_BOTTOM_GUA_ANG,SERVO_SPEED_NORMAL);
		wait1Msec(2000);
		while(right_arm_pos>1600)
		{
			arm_right_down(100);
			right_arm_pos=get_arm_right_pos();
		}
		arm_right_stop();
		servo_right_hand_top_MoveToDeg(HAND_RIGHT_TOP_JIE_ANG,SERVO_SPEED_NORMAL);
		servo_right_hand_bottom_MoveToDeg(HAND_RIGHT_BOTTOM_JIE_ANG,SERVO_SPEED_NORMAL);
		wait1Msec(1000);
		while(right_arm_pos>50)
		{
			arm_right_down(100);
			right_arm_pos=get_arm_right_pos();
		}
		arm_right_stop();
	}
	else if((hongwai<8) && (hongwai>4))
	{
		auto_left();
		while(left_arm_pos<2000)
		{
			arm_left_up(100);
			left_arm_pos=get_arm_left_pos();
		}
		arm_left_stop();
		servo_left_hand_top_MoveToDeg(HAND_LEFT_TOP_GUA_ANG,SERVO_SPEED_NORMAL);
		servo_left_hand_bottom_MoveToDeg(HAND_LEFT_BOTTOM_GUA_ANG,SERVO_SPEED_NORMAL);
		wait1Msec(2000);
		while(left_arm_pos>1600)
		{
			arm_left_down(100);
			left_arm_pos=get_arm_left_pos();
		}
		arm_left_stop();
		servo_left_hand_top_MoveToDeg(HAND_LEFT_TOP_JIE_ANG,SERVO_SPEED_NORMAL);
		servo_left_hand_bottom_MoveToDeg(HAND_LEFT_BOTTOM_JIE_ANG,SERVO_SPEED_NORMAL);
		wait1Msec(1000);
		while(left_arm_pos>50)
		{
			arm_left_down(100);
			left_arm_pos=get_arm_left_pos();
		}
		arm_left_stop();
	}
	else if((hongwai==1) || (hongwai==2))
	{
		auto_right();
		while(right_arm_pos<2000)
		{
			arm_right_up(100);
			right_arm_pos=get_arm_right_pos();
		}
		arm_right_stop();
		servo_right_hand_top_MoveToDeg(HAND_RIGHT_TOP_GUA_ANG,SERVO_SPEED_NORMAL);
		servo_right_hand_bottom_MoveToDeg(HAND_RIGHT_BOTTOM_GUA_ANG,SERVO_SPEED_NORMAL);
		wait1Msec(2000);
		while(right_arm_pos>1600)
		{
			arm_right_down(100);
			right_arm_pos=get_arm_right_pos();
		}
		arm_right_stop();
		servo_right_hand_top_MoveToDeg(HAND_RIGHT_TOP_JIE_ANG,SERVO_SPEED_NORMAL);
		servo_right_hand_bottom_MoveToDeg(HAND_RIGHT_BOTTOM_JIE_ANG,SERVO_SPEED_NORMAL);
		wait1Msec(1000);
		while(right_arm_pos>50)
		{
			arm_right_down(100);
			right_arm_pos=get_arm_right_pos();
		}
		arm_right_stop();

	}
}

