#pragma config(Hubs, S1, HTMotor, HTMotor, HTMotor, HTServo)
#pragma config(Sensor, S2, sensor_arm_left_angle, sensorI2CCustom)
#pragma config(Sensor, S3, sensor_arm_right_angle, sensorI2CCustom)
#pragma config(Sensor, S4, HTSPB, sensorI2CCustom9V)
#pragma config(Motor, motorA, nxtmotor_flapper_left, tmotorNXT, PIDControl, encoder)
#pragma config(Motor, motorB, nxtmotor_flapper_right, tmotorNXT, PIDControl, encoder)
#pragma config(Motor, motorC, nxtmotor_JSG, tmotorNXT, PIDControl, encoder)
#pragma config(Motor, mtr_S1_C3_1, drive_motor_1, tmotorTetrix, openLoop)
#pragma config(Motor, mtr_S1_C3_2, drive_motor_2, tmotorTetrix, openLoop)
#pragma config(Motor, mtr_S1_C1_1, arm_motor_left, tmotorTetrix, openLoop)
#pragma config(Motor, mtr_S1_C1_2, arm_motor_right, tmotorTetrix, openLoop)
#pragma config(Motor, mtr_S1_C2_1, drive_motor_3, tmotorTetrix, openLoop)
#pragma config(Motor, mtr_S1_C2_2, drive_motor_4, tmotorTetrix, openLoop)
#pragma config(Servo, srvo_S1_C4_1, servo_clip_right, tServoStandard)
#pragma config(Servo, srvo_S1_C4_2, servo_clip_left, tServoStandard)
#pragma config(Servo, srvo_S1_C4_3, servo_left_hand_bottom, tServoStandard)
#pragma config(Servo, srvo_S1_C4_4, servo_left_hand_top, tServoStandard)
#pragma config(Servo, srvo_S1_C4_5, servo_right_hand_bottom, tServoStandard)
#pragma config(Servo, srvo_S1_C4_6, servo_right_hand_top, tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard !!*//

/////////////////////////////////////////////////////////////////////////////////////////
// R2 headers
/////////////////////////////////////////////////////////////////////////////////////////

#include "R2_const.h"

// Global Variable for Robot
int arm_left_pos = 0;
int arm_right_pos = 0;

int arm_clip_pos = ARM_CLIP_PARK;
int flipper_pos = FLIPPER_DOWN;
int JSG_target = 0;

int sensor_IR=sensor_arm_left_angle;

bool btn_start_pressed=false;
bool btn_pause_pressed=false;

bool last_btn_start_pressed=false;
bool last_btn_pause_pressed=false;

int left_hand_bottom_pos = HAND_CLOSE;
int left_hand_upper_pos = HAND_UP;
int right_hand_bottom_pos = HAND_CLOSE;
int right_hand_upper_pos = HAND_UP;
TTimers timer_clipping = T3;
TTimers timer_R2_sys = T4;
int timer_flipping;
int timer_JOY2_BUTTON_X;
int timer_JOY2_BUTTON_B;


#include <JoystickDriver.c>
#include "drivers/hitechnic-angle.h"
#include "drivers/HTSPB-driver.h"
#include "drivers/hitechnic-irseeker-v2.h"
#include "R2_lib.h"
/////////////////////////////////////////////////////////////////////////////////////////

void display_program_info()
{
  eraseDisplay();
  nxtDisplayCenteredTextLine(1, "FTc tEaM 1032");
  nxtDisplayCenteredTextLine(3, "Compatetion Program");
	nxtDisplayCenteredTextLine(4, "ver:3");
	nxtDisplayCenteredTextLine(5, "2013.1");
	nxtDisplayCenteredTextLine(7, "dAdAlElE");
	wait1Msec(3000);
	eraseDisplay();
};


void init()
{
  RunAt(0, 0, 0);

  motor[nxtmotor_flapper_left] = 0; // reset the Motor Encoder of Motor B
	nMotorEncoder[nxtmotor_flapper_left] = 0; // reset the Motor Encoder of Motor B

	motor[nxtmotor_flapper_right] = 0; // reset the Motor Encoder of Motor C
  nMotorEncoder[nxtmotor_flapper_right] = 0; // reset the Motor Encoder of Motor C

  motor[nxtmotor_JSG] = 0; // reset the Motor Encoder of Motor C
  nMotorEncoder[nxtmotor_JSG] = 0; // reset the Motor Encoder of Motor C


	arm_pickup_park();
	hand_all_close();

  init_IR_sensor();
  init_prototype_board();

  wait1Msec(2000);

  ClearTimer(timer_R2_sys);
  timer_JOY2_BUTTON_X=0;
  timer_JOY2_BUTTON_B=0;

  ClearTimer(timer_clipping);
};


void init_arm_pos()
{
	/*
	bool arm_left_touch_bottom, arm_right_touch_bottom;
	ClearTimer(T1);
	arm_left_touch_bottom=is_arm_left_touch_bottom();
	arm_right_touch_bottom=is_arm_right_touch_bottom();

  while(true)
	{
    nxtDisplayTextLine(0, "%d, %d",arm_left_touch_bottom, arm_right_touch_bottom);
    if (arm_left_touch_bottom!=is_arm_left_touch_bottom())
    {
	    arm_left_touch_bottom=is_arm_left_touch_bottom();
	    PlaySound(soundBeepBeep);
	  };
	  if (arm_right_touch_bottom!=is_arm_right_touch_bottom())
	  {
	    arm_right_touch_bottom=is_arm_right_touch_bottom();
      PlaySound(soundBeepBeep);
    };

    if (arm_left_touch_bottom & arm_right_touch_bottom)
      break;

    if (time1[T1]>1000)
    {
      PlaySound(soundBlip);
      ClearTimer(T1);
    };
  };
  */
  reset_angle_sensor();
}

#include "R2-TELEOP.c"
#include "R2-AUTO.c"

task main()
{

  // all code will be ignored when joystick in stop mode
  PlaySound(soundUpwardTones);
  init();
  checkExternalBatt();
	PlaySound(soundDownwardTones);

  while (joystick.StopPgm)
  {
    getJoystickSettings(joystick);
    PlaySound(soundBlip);
    nxtDisplayTextLine(2, "Standing By");
    wait1Msec(50);
  }

  if (!joystick.UserMode) // Autonomous Mode or skip to human control
  {
    PlaySound(soundBeepBeep);
  	init_arm_pos();
    AutoRun();
    while(true)
    {
      getJoystickSettings(joystick);
      if (joystick.StopPgm)
        break;
      if (joystick.UserMode)
				break;
    }
  };

  while (joystick.StopPgm)
  {
   	RunAt(0,0,0);
    getJoystickSettings(joystick);
    PlaySound(soundBeepBeep);
    nxtDisplayTextLine(2, "Standing By");
    wait1Msec(50);
  }
  TeleOp();
}
