const int JOY_BUTTON_X=01;
const int JOY_BUTTON_A=02;
const int JOY_BUTTON_B=03;
const int JOY_BUTTON_Y=04;
const int JOY_BUTTON_LB=05;
const int JOY_BUTTON_RB=06;
const int JOY_BUTTON_LT=07;
const int JOY_BUTTON_RT=08;
const int JOY_BUTTON_J1_CLICK=11;
const int JOY_BUTTON_J2_CLICK=12;
const int JOY_BUTTON_TOPHAT_UP= 0;
const int JOY_BUTTON_TOPHAT_UP_RIGHT= 1;
const int JOY_BUTTON_TOPHAT_RIGHT= 2;
const int JOY_BUTTON_TOPHAT_DOWN_RIGHT= 3;
const int JOY_BUTTON_TOPHAT_DOWN= 4;
const int JOY_BUTTON_TOPHAT_DOWN_LEFT= 5;
const int JOY_BUTTON_TOPHAT_LEFT= 6;
const int JOY_BUTTON_TOPHAT_UP_LEFT= 7;

const int BUTTON_CLICK_DELAY=300;

const int HAND_LEFT_TOP_JIE_ANG=50;
const int HAND_LEFT_BOTTOM_JIE_ANG=5;
const int HAND_LEFT_TOP_GUA_ANG=110; //140;
const int HAND_LEFT_BOTTOM_GUA_ANG=180;

const int HAND_RIGHT_TOP_JIE_ANG=63;
const int HAND_RIGHT_BOTTOM_JIE_ANG=175;
const int HAND_RIGHT_TOP_GUA_ANG=110; //93;
const int HAND_RIGHT_BOTTOM_GUA_ANG=00;

const int HAND_JIE = 1;
const int HAND_GUA = 2;

const int ARM_CLIP_PARK    = 1;
const int ARM_CLIP_RELEASE = 2;
const int ARM_CLIP_CLIP    = 3;



const int ARM_LEFT_MIN=10;
const int ARM_LEFT_MAX=2000;
const int ARM_LEFT_SAFE_POS=600;
const int ARM_LEFT_OPEN_POS=1000;

const int ARM_RIGHT_MIN=10;
const int ARM_RIGHT_MAX=2000;
const int ARM_RIGHT_SAFE_POS=600;
const int ARM_RIGHT_OPEN_POS=1000;

const int ARM_TARGET_NONE   = -1;
const int ARM_TARGET_LEVEL1 = 800;
const int ARM_TARGET_LEVEL2 = 1200;
const int ARM_TARGET_LEVEL3 = 1600;


const int SERVO_SPEED_VERY_SLOW	=	1;
const int SERVO_SPEED_SLOW			=	3;
const int SERVO_SPEED_NORMAL		=	5;
const int SERVO_SPEED_FAST			=	7;
const int SERVO_SPEED_VERY_FAST	=	9;
