#pragma config(Hubs,  S1, HTMotor,  HTServo,  HTMotor,  HTMotor)
#pragma config(Sensor, S2,     arm_left_angle, sensorI2CCustom)
#pragma config(Sensor, S3,     arm_right_angle, sensorI2CCustom)
#pragma config(Sensor, S4,     HTSPB,          sensorI2CCustom9V)
#pragma config(Motor,  mtr_S1_C1_1,     drive_motor_1, tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     drive_motor_2, tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     drive_motor_3, tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     drive_motor_4, tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     arm_motor_left, tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     arm_motor_right, tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C2_1,    servo_clip_left,      tServoStandard)
#pragma config(Servo,  srvo_S1_C2_2,    servo_clip_right,     tServoStandard)
#pragma config(Servo,  srvo_S1_C2_3,    servo_arm_left_bottom, tServoStandard)
#pragma config(Servo,  srvo_S1_C2_4,    servo_arm_left_top,   tServoStandard)
#pragma config(Servo,  srvo_S1_C2_5,    servo_arm_right_bottom, tServoStandard)
#pragma config(Servo,  srvo_S1_C2_6,    servo_arm_right_top,  tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//#include <JoystickDriver.c>
#include "drivers/hitechnic-angle.h"
#include "drivers/HTSPB-driver.h"
#include "drivers/hitechnic-irseeker-v2.h"
#include "R2_const.h"
#include "R2_lib.h"


const int MENU_PAGE_COUNT=4;
string menu[MENU_PAGE_COUNT]={
		"SETUP LEFT ARMS",
		"SETUP RIGHT ARM",
		"SETUP CLIP ARM",
		"TEST DRIVE"
};

void display_program_info(){
	eraseDisplay();
	nxtDisplayCenteredTextLine(1, "FTc tEaM 1032");
	nxtDisplayCenteredTextLine(3, "Servo Install Program");
	nxtDisplayCenteredTextLine(4, "ver:1");
	nxtDisplayCenteredTextLine(5, "2013.1");
	nxtDisplayCenteredTextLine(7, "dAdAlElE");
	wait1Msec(2000);
	eraseDisplay();
};

void display_warnning_info(){
	eraseDisplay();
	nxtDisplayTextLine(0, "   !!!WARNING!!!     ");
	nxtDisplayTextLine(1, "                     ");
	nxtDisplayTextLine(2, " LIFT TWO ARM ABOVE  ");
	nxtDisplayTextLine(3, "     THE RACK        ");
	nxtDisplayTextLine(4, "                     ");
	nxtDisplayTextLine(5, "   PRESS BUTTON...   ");
	nxtDisplayTextLine(6, "                     ");
	nxtDisplayTextLine(7, "   !!!WARNING!!!     ");
	while (nNxtButtonPressed == kEnterButton) {
	};
};

void call_function(int n){
};




task main() {
	int nCycles = 0;
	nNxtButtonTask  = -2;   // Grab control of the buttons. '-3' is invalid for task, so no task will be
	                        // executed when a button is pressed.
	nNxtExitClicks  = 3; // Triple clicking EXIT button will terminate program

	TickTimer=nSysTime;

  Init();

	while (true) {
		TButtons nBtn;

		while (true){ // wait for button press
	  	nBtn = nNxtButtonPressed;
	    if ((nSysTime-TickTimer) > 250) {
	      TimeTick();
	      TickTimer=nSysTime;
	    }
     	updateScreen();
	  	if (nBtn != -1)
	  	  break;
	  }

	  switch (nBtn) {
	  	case kLeftButton:	  ++nLeftButton;   menu_level_up();  			break;
			case kRightButton:	++nRightButton;  menu_enter(); 					break;
			case kEnterButton:	++nEnterButton;  menu_enter(); 					break;
			case kExitButton:	  ++nExitButton;   menu_level_up()				break;
			default:            ++nNoButton;          break;
		}
	  while (true) { // wait for button release
	  	nBtn = nNxtButtonPressed;
	  	if (nBtn == -1)
	  	  break;
	  }
  }
	return;
}
