#pragma config(Hubs,  S1, HTMotor,  HTServo,  HTMotor,  HTMotor)
#pragma config(Sensor, S2,     arm_left_angle, sensorI2CCustom)
#pragma config(Sensor, S3,     arm_right_angle, sensorI2CCustom)
#pragma config(Sensor, S4,     HTSPB,          sensorI2CCustom9V)
#pragma config(Motor,  mtr_S1_C1_1,     drive_motor_1, tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     drive_motor_2, tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     drive_motor_3, tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     drive_motor_4, tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     arm_motor_left, tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     arm_motor_right, tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C2_1,    servo_clip_left,      tServoStandard)
#pragma config(Servo,  srvo_S1_C2_2,    servo_clip_right,     tServoStandard)
#pragma config(Servo,  srvo_S1_C2_3,    servo_arm_left_bottom, tServoStandard)
#pragma config(Servo,  srvo_S1_C2_4,    servo_arm_left_top,   tServoStandard)
#pragma config(Servo,  srvo_S1_C2_5,    servo_arm_right_bottom, tServoStandard)
#pragma config(Servo,  srvo_S1_C2_6,    servo_arm_right_top,  tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*   HiTechnic Experimenter's Kit for the SuperPro

Experiment - 1 Introduction
Read the status of a switch and display the status on an LED
asdfasfasdfasdfasdf

*/

#include "drivers/hitechnic-angle.h"
#include "drivers/HTSPB-driver.h"
#include "drivers/hitechnic-irseeker-v2.h"
#include "R2_const.h"
#include "R2_lib.h"

void display_program_info(){
	eraseDisplay();
	nxtDisplayCenteredTextLine(1, "FTc tEaM 1032");
	nxtDisplayCenteredTextLine(3, "PrototypeBRD Test");
	nxtDisplayCenteredTextLine(4, "ver:1");
	nxtDisplayCenteredTextLine(5, "2013.1");
	nxtDisplayCenteredTextLine(7, "dAdAlElE");
	wait1Msec(3000);
	eraseDisplay();
};


task main() {
	display_program_info();
  int inputdata;

  HTSPBsetupIO(HTSPB, 0xff);
	HTSPBwriteIO(HTSPB, 0xff);

  // Set B0 for input
  HTSPBsetupIO(HTSPB, 0x00);

  while(true) {
    // Read a 10bit wide analogue value from A0
    inputdata = HTSPBreadADC(HTSPB, 0, 10);
    nxtDisplayTextLine(1, "Weitht(A0): %d", inputdata);

    inputdata = HTSPBreadADC(HTSPB, 1, 10);
    nxtDisplayTextLine(2, "Weight(A1): %d", inputdata);

		inputdata= HTSPBreadIO(HTSPB, 0xff);
    nxtDisplayTextLine(4, "B: %x", inputdata);

    char buf[9];
    int i;
    for (i=0; i<8; i++){
    	if ((inputdata & 0x80)==0x80) buf[i]='1' ; else buf[i]='0';
    	inputdata= inputdata<<1;
    };
    buf[8]=0x00;
    string str="";
    StringFromChars(str, buf);
    nxtDisplayTextLine(5, "H[%s]L", str);

    wait1Msec(50);
  }


}
